### ISSUE TITLE
Have default for title subtitle and spacing.

### ISSUE THREAD

**Issue by deepxd** [MarkyC/Tab2PDF#46]
> For the correct input file like input-1.txt (posted on course webpage) BUT WITHOUT ANY HEADER INFORMATION, software replaced the Title and Sub-Title strings with "No Title" and "No Subtitle" which is GOOD but it used SPACING=5 as default whereas no information about the spacing was provided. User should have known this that default spacing is set to five (5)

If there is no title or subtitle or spacing provided then we should have a popup message that informs the user that the default spacing is set to 5 and that there was no title or subtitle provided.

**Comment by MarkyC** [comment]
not implemented using a popup, but the text fields say no title and no subtitle when the title/subtitle are empty. I feel this can be marked fixed
