### ISSUE TITLE
run() method in PdfCreator.java is not functional

### ISSUE THREAD

**Issue by deepxd** [MarkyC/Tab2PDF#52]
>In the PdfCreator.java file under the run() method, you are opening the created pdf file at the end but this thing is not functional and the reason is very same that it tries to locate for a file <filename.pdf> but unable to find a file with the given name with ".pdf" extension and hence fail to open it. Once you will apply the above fix, this thing will also start functioning properly.

this links to the issue #51

**Comment by MarkyC** [comment]
fixed this in the latest update
