### ISSUE TITLE
Implement User Manual

### ISSUE THREAD

**Issue by MarkyC** [MarkyC/Tab2PDF#58]
How you do it is up to you

**Comment by MarkyC** [comment]
Why is this closed? There's no pull request to merge. Let me know what's up

On Mon, Mar 23, 2015 at 12:15 PM, papaiza <notifications@github.com> wrote:

> Closed #58 <https://github.com/MarkyC/Tab2PDF/issues/58>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarkyC/Tab2PDF/issues/58#event-262502477>.
>



-- 
Marco Cirillo

**Comment by papaiza** [comment]
Sorry boss. Forgot to make pull request, but it is done.
