### ISSUE TITLE
Preview Panel Issue

### ISSUE THREAD

**Issue by Sitiugin** [MarkyC/Tab2PDF#65]
When you open a tab file while Preview Panel is selected, the converted Pdf file is not shown in the preview panel until you switch to editor panel and back.
![screenshot 70](https://cloud.githubusercontent.com/assets/10438349/6973363/49fc3e90-d958-11e4-9728-d0e14c90741f.png)

**Comment by MarkyC** [comment]
Ended up fixing this with a 1-liner

```
new PreviewTabListener(this).stateChanged(new ChangeEvent(getTabbedPane()));
```
