### ISSUE TITLE
Add Easter Egg to About Window

### ISSUE THREAD

**Issue by MarkyC** [MarkyC/Tab2PDF#78]
Everyone comment with two pictures:

* One stoic face
* One happy face

Deep and Anton will add them to the About window, with a listener that changes between stoic and smiley face when the picture is clicked

**Comment by MarkyC** [comment]
![Imgur](http://i.imgur.com/qBR3ddW.png)
![Imgur](http://i.imgur.com/RuYy8wR.png)

**Comment by varsharagav** [comment]
![img_1091](https://cloud.githubusercontent.com/assets/6807514/7194355/8b9c15e0-e47b-11e4-945e-999de9899ac3.JPG)
![img_1090](https://cloud.githubusercontent.com/assets/6807514/7194354/8b987ad4-e47b-11e4-813b-0c7e3866d233.JPG)
